In [34]:
from data_split import *
from feature_engineering import *
from matrix_tools import *
from model import *
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [35]:
import sklearn
print(sklearn.__version__)

1.5.1


In [36]:
import numpy as np
import pandas as pd

In [53]:
df = pd.read_csv('../data/student/student-por.csv',sep=';')

In [54]:
encoder = OH()
split = RandomSplit()
PCA = PrincipalComponentAnalysis() # Question : Why if i apply PCA on the entire dataset (target included) I get a perfect score?
log = LogTransformation()

df = encoder.apply_transformation(df)
df.head()

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  \
0   18     4     4           2          2         0       4         3      4   
1   17     1     1           1          2         0       5         3      3   
2   15     1     1           1          2         0       4         3      2   
3   15     4     2           1          3         0       3         2      2   
4   16     3     3           1          2         0       4         3      2   

   Dalc  ...  activities_no  activities_yes  nursery_no  nursery_yes  \
0     1  ...            1.0             0.0         0.0          1.0   
1     1  ...            1.0             0.0         1.0          0.0   
2     2  ...            1.0             0.0         0.0          1.0   
3     1  ...            0.0             1.0         0.0          1.0   
4     1  ...            1.0             0.0         0.0          1.0   

   higher_no  higher_yes  internet_no  internet_yes  romantic_no  romantic_yes  
0        0.0         1.0          1.0           0.0          1.0           0.0  
1        0.0         1.0          0.0           1.0          1.0           0.0  
2        0.0         1.0          0.0           1.0          1.0           0.0  
3        0.0         1.0          0.0           1.0          0.0           1.0  
4        0.0         1.0          1.0           0.0          1.0           0.0  

[5 rows x 59 columns]

In [55]:
X_train, X_test, y_train, y_test = split.split_data(df)
X_train = log.apply_transformation(X_train)
X_test = log.apply_transformation(X_test)


In [56]:
model = LinearRegression_test()
theta = model.train_model(X_train, y_train)
y_pred=model.predict(X_test, theta)
print(y_pred)
print(y_test)

[[11.91636206 12.87576094 13.08229377]
 [11.81808828 11.86061592 12.69736389]
 [12.98816369 14.08790265 14.17597059]
 [10.89585873 11.77578106 11.70987759]
 [10.22435531  9.87157529 10.31388502]
 [11.91959434 12.4189915  12.85938297]
 [13.3301409  13.34219049 13.87191532]
 [ 7.59263865  7.19389885  7.35118945]
 [11.52420086 11.74151455 12.72989694]
 [11.83140821 11.88421846 12.48016864]
 [12.1226539  12.22516202 12.69889359]
 [11.7653762  11.38769459 11.64260874]
 [13.19877848 13.19290248 13.57285872]
 [11.45406576 11.54819    11.73578226]
 [ 9.99010376  9.80996851  9.37096377]
 [13.81288674 14.67469406 15.31067234]
 [12.60585255 13.03434092 13.46778807]
 [ 9.04763398 10.69261896 11.19629821]
 [12.95611661 13.06162909 13.67552079]
 [13.18627393 13.16158207 13.95312405]
 [12.41859407 12.88152041 13.25500406]
 [11.45213598 11.14290974 11.42204573]
 [13.46364763 14.66823805 15.81594085]
 [12.5697064  12.58889763 12.41048066]
 [11.44743897 10.95438565 10.73036912]
 [12.5661117  13.37503461

In [57]:
print("Mean Squared Error: ", model.evaluate(y_pred,y_test))

Mean Squared Error:  7.6121441696866405
